SH_STAGE_SAPLING = 0
SH_STAGE_YOUNG = 0
SH_STAGE_MATURE = 0
SH_STAGE_ROTTING = 0

MH_STAGE_SAPLING = 0
MH_STAGE_YOUNG = 0
MH_STAGE_MATURE = 0
MH_STAGE_ROTTING = 0

SD_STAGE_SAPLING = 0
SD_STAGE_YOUNG = 0
SD_STAGE_MATURE = 0
SD_STAGE_ROTTING = 0